export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const CATALOG_ROUTE = '/'
export const MOVIEBASKET_ROUTE = '/moviebasket'
export const FILM_ROUTE = '/film'